### PR TITLE
Remove jQuery and js-cookie libraries from the blog

### PR DESCRIPTION
**Pull request by gunjam**
Rewritten accessibility-tool.js to no longer rely on jQuery and js-cookie.

After removing the two libraries from the front end it's saving about 70KB of JS being sent to the browser.

### CODE REVIEW

**Comment by gunjam** [comment]
Please test this in case I broke it all 😉

**Comment by abbott567** [comment]
Gulp is only running in the dev dependencies. If I put the compiled files in the .gitignore they won't get deployed to heroku.

**Comment by gunjam** [comment]
You could set your npm start script to be your gulp tasks.

**Comment by abbott567** [comment]
I'll give that a bash next. Cheers

**Pull request merged**
